### PR TITLE
doc: fix typo mistake

### LINKED ISSUE #1: Fix typo mistake

### PR DESCRIPTION
**Pull request by longqua69**
Closes #1

### CODE REVIEW

**Review by cyntler — COMMENTED** [review]
LGTM!

**Comment by saviomartin** [comment]
No need for a PR for this. You just changed one word.

**Comment by ilyasbabu** [comment]
> No need for a PR for this. You just changed one word.

That's insolent. I too found another typo, I just can't PR because of this impoliteness.

**Comment by saviomartin** [comment]
> > No need for a PR for this. You just changed one word.
> 
> That's insolent. I too found another typo, I just can't PR because of this impoliteness.

Hey, I'm just trying to keep up with the standard of PRs and promote genuine contributions. I'm sorry if my way hurts you

**Pull request closed without merging**
